### PR TITLE
Add more global attributes

### LINKED ISSUE #19: missing global attributes
Some global attributes are missing in HIRS.  Currently I'm adding those manually but they should be in the template and format document.  I would expect that some if not all of them should be in all FCDRs!  Most are from the CF conventions, CF standard names, or ACDD conventions.

* `author`
* `email` or `contact`
* `satellite`
* `url`
* `fcdr_software_version`
* `data_version`
* `time_coverage_start`
* `time_coverage_end`

### PR DESCRIPTION
**Pull request by gerritholl**
Add more global attributes to FCDRs, some new, some copied from CDRs

Fixes #19.

### CODE REVIEW

**Review by TomBlock — COMMENTED** [review]
Gerrit, this affects all FCDRs - we need to have a confirmation by all sensor teams that this is desired.
Will not merge before this has happened. Do you send the mail to the team/Chris/Rhona?

**Comment by gerritholl** [comment]
Ok, we should discuss that.  Otherwise we just do it for HIRS?  I've had those in my version for a long time but was only recently reminded I shouldn't add attributes in my code if they're not in the template.

**Comment by gerritholl** [comment]
Implicitly, we have discussed this last year in a format review, but that just affected HIRS.

**Comment by TomBlock** [comment]
No problem to keep it for HIRS only - but the way you updated the code affects all sensors. This includes an exception raised if fields are not filled with data - so that would be a mean surprise to the others.

**Comment by gerritholl** [comment]
Is there a method already to put sensor-specific global attributes?  I did not find it.  We could put it there until and unless we reach consensus that everybody should provide this information (which I think they should, but it is indeed a project decision).

**Comment by TomBlock** [comment]
You can add these variables in 
https://github.com/FIDUCEO/FCDRTools/blob/master/fiduceo/fcdr/writer/templates/hirs.py

def add_original_variables(dataset, height, srf_size=None):

This method is called by all the HIRS2/3/4 sub-classes

**Comment by gerritholl** [comment]
Ah, I didn't put the global attributes there because they're global attributes and not data variables, but it would work from a code point of view.  I'll leave this PR open for now, if the email I sent results in the conclusion they should be in all FCDRs I leave it here, otherwise I'll move those lines to where you suggest.

**Comment by TomBlock** [comment]
Absolutely right, that would be a quick hack. You could add a method to the HIRS class that explicitely adds the global attributes and call this from the writer createTemplateXXX() methods.

sensor_template.add_specifc_global_metadata(dataset)

and supply an empty "do-nothing" implementation for the other sensors

**Comment by gerritholl** [comment]
@TomBlock  Does it look better to you this way?  It's a bit dirty with 8 commits, do you care about this and should I squash them, or is it OK either way?

**Pull request merged**
